#!/usr/bin/env bash
ln -sf AArch64/{*.ml{,i},libmincaml.S} .
cp AArch64/globals.s min-rt/
cd test; ln -sf AArch64/{,too}manyargs.ml .; cd ..
cd shootout; ln -sf AArch64/Makefile .; cd ..
cd bytemark; ln -sf AArch64/Makefile .; cd ..
